# This rule is not used by the project namespacelabel-assignment-shv itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to namespacelabel.dana.exam resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: namespacelabel-assignment-shv
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: namespacelabel-viewer-role
rules:
- apiGroups:
  - namespacelabel.dana.exam
  resources:
  - namespacelabels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - namespacelabel.dana.exam
  resources:
  - namespacelabels/status
  verbs:
  - get
